In [1]:
import numpy as np
import math
import pandas as pd

# Matrix with vector multiplication

In [2]:
A = np.array([[1,2,3],[4,5,6]])
v = np.array([2,4,6])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
v

array([2, 4, 6])

In [5]:
np.dot(A,v)

array([28, 64])

In [8]:
v.reshape(-1,1)

array([[2],
       [4],
       [6]])

In [9]:
np.dot(A,v.reshape(-1,1))

array([[28],
       [64]])

# Exponential operation of vectors

In [12]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
v = np.array([1,2,3])

In [16]:
math.exp(v)

TypeError: only size-1 arrays can be converted to Python scalars

In [17]:
math.exp(v[1])

7.38905609893065

In [18]:
np.exp(v)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [19]:
np.exp(v*np.log(2))

array([2., 4., 8.])

# Maximum

In [23]:
np.maximum([1,2,-3], 0)

array([1, 2, 0])

# Broadcasting

In [27]:
A = np.array([[1,2,3,4],[0,2,4,6],[3,6,9,12],[4,5,6,7]])
A

array([[ 1,  2,  3,  4],
       [ 0,  2,  4,  6],
       [ 3,  6,  9, 12],
       [ 4,  5,  6,  7]])

In [36]:
cal = A.sum(axis=0)
cal

array([ 8, 15, 22, 29])

In [32]:
# compare to pandas
dfA = pd.DataFrame(A)
dfA

0  1  2   3
0  1  2  3   4
1  0  2  4   6
2  3  6  9  12
3  4  5  6   7

In [33]:
dfA.sum()

0     8
1    15
2    22
3    29
dtype: int64

In [34]:
dfA.sum(axis=0)

0     8
1    15
2    22
3    29
dtype: int64

In [35]:
dfA.sum(axis=1)

0    10
1    12
2    30
3    22
dtype: int64

In [37]:
A/cal

array([[0.125     , 0.13333333, 0.13636364, 0.13793103],
       [0.        , 0.13333333, 0.18181818, 0.20689655],
       [0.375     , 0.4       , 0.40909091, 0.4137931 ],
       [0.5       , 0.33333333, 0.27272727, 0.24137931]])

In [40]:
A

array([[ 1,  2,  3,  4],
       [ 0,  2,  4,  6],
       [ 3,  6,  9, 12],
       [ 4,  5,  6,  7]])

In [41]:
A/2

array([[0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. ],
       [1.5, 3. , 4.5, 6. ],
       [2. , 2.5, 3. , 3.5]])

In [43]:
np.random.rand(8)

array([-0.38824607,  1.290012  ,  0.42255911, -0.11620041,  0.00217573,
       -0.18877197, -1.03462757, -0.00616969])

In [45]:
a = np.array([1,2,3])
a.shape

(3,)

In [8]:
math.exp(1)

2.718281828459045

In [14]:
x = np.array([[1,2,3,4],[2,4,6,8]])
x

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [15]:
np.sum(x,axis=0)

array([ 3,  6,  9, 12])

In [16]:
np.sum(x)

30

In [17]:
np.sum(x,axis=1)

array([10, 20])

# Reshape

In [22]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
a.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
a.reshape(2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [26]:
b = np.arange(120).reshape(2,3,4,5)
b

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [28]:
b[0]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])