In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[4,5,6]])
v = np.array([2,4,6])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
v

array([2, 4, 6])

In [5]:
np.dot(A,v)

array([28, 64])

In [8]:
v.reshape(-1,1)

array([[2],
       [4],
       [6]])

In [9]:
np.dot(A,v.reshape(-1,1))

array([[28],
       [64]])