In [1]:
import numpy as np

## 1. Create an array

### a. From list to 1d and 2d

#### 1 list is consider as a vector, and vector is written as a row
####  remember: number of rows = number of vectors (lists)

In [2]:
l1=[1,2,3]  # 1 vector as a row

In [4]:
np.array(l1) 

array([1, 2, 3])

In [5]:
l2=[[1,2,3],[4,5,6]] # 2 vectors as 2 rows

In [6]:
np.array(l2) # matrix 2x3

array([[1, 2, 3],
       [4, 5, 6]])

### b. `arange` and `linspace` 

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2,15,3) # requires integer

array([ 2,  5,  8, 11, 14])

In [9]:
np.linspace(1,20,4) # 4 is number of elements, not interval. Linspace includes both 2 ends

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [10]:
np.linspace(.5,20.7,14)

array([ 0.5       ,  2.05384615,  3.60769231,  5.16153846,  6.71538462,
        8.26923077,  9.82307692, 11.37692308, 12.93076923, 14.48461538,
       16.03846154, 17.59230769, 19.14615385, 20.7       ])

### c. same numbers

#### pass in a tuple

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,4)) # require a tuple  row x columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
# from two and above, doesn't work
np.twos((4,6))

AttributeError: module 'numpy' has no attribute 'twos'

### d. Identity matrix

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### e. Random numbers

#### pass in a tuple without brackets

In [20]:
# uniform in (0,1)
np.random.rand(5)

array([0.32235797, 0.69412427, 0.15708232, 0.79940546, 0.69127177])

In [21]:
np.random.rand(4,3)

array([[0.75120374, 0.85549525, 0.18828601],
       [0.86065497, 0.64435525, 0.4946224 ],
       [0.09835519, 0.76697819, 0.27321404],
       [0.41493307, 0.98956468, 0.45914902]])

In [24]:
# Gaussian centered around 0
np.random.randn(3)

array([-1.18849907,  0.15156489,  0.95353554])

In [28]:
np.random.randn(3,5)

array([[-0.4011198 , -1.17855018, -0.43604256, -1.93556074, -1.25909958],
       [-0.27725478, -0.29845781, -0.04316646,  0.7814796 ,  1.15456417],
       [ 0.11000619,  0.44155799, -0.5805231 , -2.1227377 ,  2.17459509]])

In [34]:
# random integers between a and b, b not counted
np.random.randint(5)

4

In [37]:
np.random.randint(2,5,6) # 6 is the number of random integers

array([3, 4, 3, 4, 2, 2])

### f. Reshape

In [2]:
arr=np.arange(10,45,3)
arr

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43])

In [3]:
arr.shape # it should be (1,12), not (12,)

(12,)

In [40]:
arr.reshape(3,4)

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [41]:
arr.reshape(4,3)

array([[10, 13, 16],
       [19, 22, 25],
       [28, 31, 34],
       [37, 40, 43]])

In [54]:
arr.reshape(4,3).shape

(4, 3)

In [42]:
arr.min()

10

In [43]:
arr.max()

43

### g. difference shape (a,1) and (a, ) and (1, a)

#### 1d array is considered as having no columns, thats why (a, )

In [4]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a.shape

(10,)

In [6]:
a.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
a.reshape(1,10).shape

(1, 10)

In [10]:
a.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
a.reshape(10,1).shape

(10, 1)

### 2d array

In [12]:
m=np.random.rand(20).reshape(4,5)
m

array([[0.02237716, 0.52468379, 0.47559836, 0.36453368, 0.98361764],
       [0.70446026, 0.58600101, 0.22904905, 0.43576993, 0.86638441],
       [0.95927707, 0.67477675, 0.44941259, 0.42124063, 0.48033618],
       [0.34105909, 0.39645199, 0.09632926, 0.19487326, 0.99306663]])

In [13]:
m[:,0]

array([0.02237716, 0.70446026, 0.95927707, 0.34105909])

In [14]:
m[:,0].shape

(4,)

### tip to make columns, a:a+1

In [18]:
m[:,0:1]

array([[0.02237716],
       [0.70446026],
       [0.95927707],
       [0.34105909]])

In [19]:
m[:,0:1].shape

(4, 1)

### more dimensions

In [21]:
m=np.random.randint(1,100,30)
m

array([62, 73, 62, 77, 14, 95, 16, 69, 85, 10, 55, 49, 43, 36, 18,  2, 94,
       99, 79, 59, 66, 79, 47, 45, 12, 77, 51, 38, 65,  3])

In [24]:
m.reshape(1,30)

array([[62, 73, 62, 77, 14, 95, 16, 69, 85, 10, 55, 49, 43, 36, 18,  2,
        94, 99, 79, 59, 66, 79, 47, 45, 12, 77, 51, 38, 65,  3]])

In [25]:
m.reshape(5,6)

array([[62, 73, 62, 77, 14, 95],
       [16, 69, 85, 10, 55, 49],
       [43, 36, 18,  2, 94, 99],
       [79, 59, 66, 79, 47, 45],
       [12, 77, 51, 38, 65,  3]])

In [23]:
m1=m.reshape(2,3,5) # from behind, nr of cols then nr of rows then nr of groups
m1

array([[[62, 73, 62, 77, 14],
        [95, 16, 69, 85, 10],
        [55, 49, 43, 36, 18]],

       [[ 2, 94, 99, 79, 59],
        [66, 79, 47, 45, 12],
        [77, 51, 38, 65,  3]]])

In [26]:
m1[0,1,3]

85

In [27]:
m1[1,2]

array([77, 51, 38, 65,  3])

## 2. Max, min and their position


In [45]:
l=np.random.randn(6)
l

array([ 0.28880107,  0.901115  , -1.00293759,  0.6775766 , -0.37079551,
       -1.15995105])

In [46]:
l.max()

0.9011149993432583

In [47]:
l.argmax()

1

In [48]:
l.min()

-1.1599510463425236

In [49]:
l.argmin()

5

## 3. Index, slice

### for 1d array, exactly the same as a list

### a. Can change value on a slice of original, but original also changes. If dont want then use `copy`

In [68]:
a=np.arange(3,38,3)
a

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])

In [69]:
len(a)

12

In [70]:
b=a[-1:1:-1]
b

array([36, 33, 30, 27, 24, 21, 18, 15, 12,  9])

In [72]:
b[-1:3:-1]=5
b

array([36, 33, 30, 27,  5,  5,  5,  5,  5,  5])

In [73]:
a  # a has change!

array([ 3,  6,  5,  5,  5,  5,  5,  5, 27, 30, 33, 36])

In [77]:
c=a.copy()
c

array([ 3,  6,  5,  5,  5,  5,  5,  5, 27, 30, 33, 36])

In [78]:
c[1:3]

array([6, 5])

In [79]:
c[1:3]=100

In [80]:
c

array([  3, 100, 100,   5,   5,   5,   5,   5,  27,  30,  33,  36])

In [81]:
a # here a and c are different. a is kept!

array([ 3,  6,  5,  5,  5,  5,  5,  5, 27, 30, 33, 36])

### b. For 2darray, use 2 index in [   ]

In [2]:
ar2d=np.random.randn(4,5)
ar2d

array([[-1.02415514,  0.85791898,  1.29900097, -0.09646545,  0.9583247 ],
       [ 2.01935654, -0.39712113,  0.83591663,  0.68356447, -0.76772702],
       [ 1.18618938, -0.38870551,  0.3338749 , -1.6116899 , -0.33438806],
       [-0.58400212, -1.0020274 , -0.37012477,  0.7066392 ,  0.36351212]])

In [91]:
ar2d[2,3] # differs index in a matrix!

-0.017829263983072507

In [92]:
ar2d[1:3,2:4]

array([[-1.16873295, -0.11475766],
       [ 0.60475178, -0.01782926]])

In [4]:
ar2d[:,0]

array([-1.02415514,  2.01935654,  1.18618938, -0.58400212])

In [5]:
ar2d[:,0].shape

(4,)

In [7]:
ar2d[:,0:1]

array([[-1.02415514],
       [ 2.01935654],
       [ 1.18618938],
       [-0.58400212]])

Note that (a,) is generic in Python, it means a tuple with only one element. 

So shape (a,) means numpy only needs one sequence to index the array.
    

### c. Filter based on condition

#### write condition in []

In [93]:
ar2d

array([[-1.19620986,  0.03342646,  0.37759918,  0.95849506, -0.77641839],
       [ 0.44594882,  1.1213059 , -1.16873295, -0.11475766, -0.01732793],
       [ 1.67283311, -1.67726901,  0.60475178, -0.01782926,  0.05582437],
       [ 1.4339236 ,  2.16538778, -0.30561939, -1.22299403,  1.34499132]])

In [98]:
ar2d>1 # return an array of same size, but values are boolean

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False, False],
       [ True,  True, False, False,  True]])

In [97]:
ar2d[ar2d>=1] # return a list

array([1.1213059 , 1.67283311, 1.4339236 , 2.16538778, 1.34499132])

In [101]:
ar2d[ar2d<=2 & ar2d>=1]

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

# 4. Operations

## a. Array and array, + - * /

In [3]:
a=np.arange(2,15,3)
a

array([ 2,  5,  8, 11, 14])

In [7]:
b=np.arange(5,25,4)
b

array([ 5,  9, 13, 17, 21])

In [8]:
a+b

array([ 7, 14, 21, 28, 35])

In [9]:
a-b

array([-3, -4, -5, -6, -7])

In [10]:
a*b

array([ 10,  45, 104, 187, 294])

In [13]:
a/b

array([0.4       , 0.55555556, 0.61538462, 0.64705882, 0.66666667])

## b. Array and scalar

### apply scalar to all elements

In [14]:
a*2

array([ 4, 10, 16, 22, 28])

In [15]:
a+2

array([ 4,  7, 10, 13, 16])

In [16]:
a-2

array([ 0,  3,  6,  9, 12])

In [17]:
a/2

array([1. , 2.5, 4. , 5.5, 7. ])

In [19]:
a/0

<ipython-input-19-deacdc4ccabc>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([inf, inf, inf, inf, inf])

## c. Universal function  ufunc

In [20]:
a

array([ 2,  5,  8, 11, 14])

In [21]:
np.sqrt(a)

array([1.41421356, 2.23606798, 2.82842712, 3.31662479, 3.74165739])

In [22]:
np.exp(a)

array([7.38905610e+00, 1.48413159e+02, 2.98095799e+03, 5.98741417e+04,
       1.20260428e+06])

In [23]:
np.log(a)

array([0.69314718, 1.60943791, 2.07944154, 2.39789527, 2.63905733])

In [24]:
l=[1,2,3,4,5,7]

We can use a defined function to take action on array, using `map(f,array)` or directly `f(array)`.

In [2]:
l=[1,2,3,4,5,7]

In [3]:
def f(x):
    return x**2

In [4]:
f(4)

16

In [5]:
map(f,l)

In [6]:
list(map(f,l))

[1, 4, 9, 16, 25, 49]

In [8]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
f(a)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [10]:
map(f,a)

In [12]:
list(map(f,a))

[1, 4, 9, 16, 25]

In [13]:
def g(x=6):
    return x%3==0

In [14]:
g()

True

In [15]:
g(5)

False

In [16]:
list(map(g,l))

[False, False, True, False, False, False]

In [17]:
filter(g,l)

In [18]:
list(filter(g,l))

[3]

# 5. Matrices

## a. Multiplication

In [2]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
b=np.arange(5,17).reshape(3,4)
b

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
np.matmul(a,b)

array([[ 62,  68,  74,  80],
       [143, 158, 173, 188]])

Another way is using `@`

In [5]:
a@b

array([[ 62,  68,  74,  80],
       [143, 158, 173, 188]])

## b. Element wise mul

In [7]:
c=np.array([[0,2,1],[3,-1,2]])
c

array([[ 0,  2,  1],
       [ 3, -1,  2]])

In [8]:
a*c

array([[ 0,  4,  3],
       [12, -5, 12]])

In [9]:
np.multiply(a,c)

array([[ 0,  4,  3],
       [12, -5, 12]])

## b. Inverse

In [24]:
b1=b[:,:3]
b1

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [25]:
np.linalg.det(b1)

-3.0061423436004183e-15

In [26]:
np.linalg.inv(b1)

array([[ 1.33060898e+15, -2.66121796e+15,  1.33060898e+15],
       [-2.66121796e+15,  5.32243592e+15, -2.66121796e+15],
       [ 1.33060898e+15, -2.66121796e+15,  1.33060898e+15]])

In [27]:
np.matmul(b1,np.linalg.inv(b1))

array([[ 1.25, -2.  , -0.25],
       [ 0.25, -2.  ,  0.75],
       [-0.75, -2.  ,  1.75]])

In [39]:
b1@np.linalg.inv(b1)

array([[ 1.25, -2.  , -0.25],
       [ 0.25, -2.  ,  0.75],
       [-0.75, -2.  ,  1.75]])

In [13]:
x = np.array([1,5,3,2,7,6])
x

# threshhold 3, turned into [0,1,0,0,1,1]  ???

array([1, 5, 3, 2, 7, 6])

In [14]:
x>3

array([False,  True, False, False,  True,  True])

In [15]:
x[x>3]

array([5, 7, 6])

In [ ]:
x